#!/bin/sh
#set -x

SCRIPT_DIR="$(dirname $(realpath "$0"))"
HOST_PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
SCRIPT_DIR="$(basename "$SCRIPT_DIR""$0")"
DOCKER_PROJECT_DIR="/home/project"

podman run --privileged --group-add keep-groups \
   --workdir "$DOCKER_PROJECT_DIR" \
   -v $HOST_PROJECT_DIR:$DOCKER_PROJECT_DIR \
   -i -t \
   wix-env-dev \
   sh 

