#!/bin/sh
set -x
THIS_DIR="$(dirname $(realpath "$0"))"
HOST_PROJECT_DIR="$(dirname "$THIS_DIR")"
DOCKER_PROJECT_DIR="/home/project"
SCRIPT_DIR="wix-env"

# podman image ls
podman build -v "$THIS_DIR/transfer:/transfer" -t wix-env-dev  - < Dockerfile

### Stop all containers with:
#docker stop $(docker ps -q)

### Remove unused images with:
# docker image prune --all

### Remove all dangling data, i.e. containers stopped, volumes excluding
### containers and images with no containers:
# docker system prune --all

