#!/bin/sh
#set -x

HOST_PROJECT_DIR="$(dirname $(pwd))"
SCRIPT_DIR="$(basename $(pwd))"
DOCKER_PROJECT_DIR="/home/project"

podman run --privileged --group-add keep-groups \
   --workdir "$DOCKER_PROJECT_DIR" \
   -v $HOST_PROJECT_DIR:$DOCKER_PROJECT_DIR \
   -i -t \
   build-env-dev \
   bash 

