#!/bin/sh

mkdir --parents ./build/html
mkdir --parents ./build/html/_downloads
mkdir --parents ./build/man/man1

# Html page
./md2docbook2pdf ./source/tp-note--manual.md ./build/pdf/tp-note--manual.pdf
./md2docbook2html ./source/tp-note--manual.md ./build/html/tp-note--manual.html

