#!/bin/sh

mkdir --parents ./build/html
mkdir --parents ./build/html/_downloads
mkdir --parents ./build/man/man1

# Html page
./docbook52pdf ./source/tp-note--manual.md ./build/pdf/tp-note--manual.pdf
./docbook52html ./source/tp-note--manual.md ./build/html/tp-note--manual.html

