#!/bin/sh
set -x

./10-clear-targets
#./11-test
./12-make-targets
./15-make-docs
./16-prepare-build-dir
# The next is using Docker:
./17-make-deb-package
./18-make-win-msi-package
./19-symlink-installer
./20-clear-targets-keep-binaries
