#!/bin/sh
# Change to this script directory
cd $(dirname "$0")

# Unit testing

if cargo test --all
then
  echo Cargo test succeeded.
else
  ( echo Cargo test failed. && exit 1 )
fi


# Functional tests

cd ../tests/functional/
./run-tests

