#!/bin/sh
# Change to this script directory
cd $(dirname "$0")
cd ..

rustup override set 1.81.0

# Cargo deb saves the built package in
# target/x86_64-unknown-linux-gnu/debian
cargo deb --package tpnote --target=x86_64-unknown-linux-gnu

#rustup target add i686-unknown-linux-gnu
#sudo apt-get install libc6-dev-i386
#cargo deb --target=i686-unknown-linux-gnu
