#!/bin/sh
 set -x
cd ..
PROJECT_DIR="$(pwd)"
BUILD_DIR="$PROJECT_DIR/target/wix"

PACKAGE_NAME="tpnote"
BIN_NAME="tpnote"
EXE_NAME="$BIN_NAME.exe"
BIN_VERSION="$(grep -e '^version' Cargo.toml | sed 's/.*"\(.*\)".*/\1/' | head -n 1)"

sudo /usr/local/bak/adjust-home_doc-permissions

cd "$BUILD_DIR"

docker run --rm --env Platform=x64 --env Version=$BIN_VERSION \
    --env CargoProfile=x86_64-pc-windows-gnu/release \
    -v "$BUILD_DIR:/wix" \
    dactiv/wix \
    candle "$BIN_NAME.wxs"

docker run -i --rm -v "$BUILD_DIR:/wix" dactiv/wix \
   light -out "$PACKAGE_NAME-$BIN_VERSION-x86_64.msi" "$BIN_NAME.wixobj" -sval



