#!/bin/bash
# Change to this script directory
cd $(dirname "$0")

# Win .msi installer
pushd ../target/wix
ls *.msi |tail -n 1| xargs -I {} ln -s {} tpnote-latest-x86_64.msi
cd ../../scripts
pushd

# Debian package
pushd ../target/x86_64-unknown-linux-gnu/debian
ls *.deb |tail -n 1| xargs -I {} ln -s {} tpnote_latest_amd64.deb
pushd

# Documentation
# (for backwards compatibility)
pushd ../docs/build/html/
echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0;url=https://blog.getreu.net/projects/tp-note/tpnote--manpage.html" /></head></html>' > tp-note--manpage.html
echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0;url=https://blog.getreu.net/projects/tp-note/tpnote--manual.html" /></head></html>' > tp-note--manual.html
pushd


