#!/bin/sh

mkdir --parents ./build/html
mkdir --parents ./build/html/_downloads
mkdir --parents ./build/man/man1

# Html page
./markdown2man ./source/tpnote--manpage.md ./build/man/man1/tpnote.1
./markdown2pdf ./source/tpnote--manpage.md ./build/pdf/tpnote--manpage.pdf
./markdown2html ./source/tpnote--manpage.md ./build/html/tpnote--manpage.html

