#!/bin/sh

mkdir --parents ./build/html
mkdir --parents ./build/html/_downloads
mkdir --parents ./build/man/man1

cd  ./build/html/_downloads
ln -sf ../../../../target/doc .
ln -sf ../../../../target/wix .
ln -sf ../../../../target/x86_64-pc-windows-gnu .
ln -sf ../../../../target/x86_64-unknown-linux-gnu .
ln -sf ../../../../target/x86_64-unknown-linux-musl .
ln -sf ../../../build/man/man1/tpnote.1.gz .


