#!/bin/sh

# Change to this script directory
cd $(dirname "$0")
rm -r ./build

# Gather input
# NB: source/README.md is a symlink to ../../README.md, so it always tracks the
# root README -- no copy needed (and `cp` would fail: same file).
cp ../assets/tpnote-screenshot.png ./source/assets
cp ../assets/tpnote.svg ./source/assets

# Build
./make--index
./make--tpnote--manpage
./make--tpnote--manual
./make--symlinks

