#!/bin/sh

# Change to this script directory
cd $(dirname "$0")
rm -r ./build

# Gather input
cp ../README.md ./source
cp ../assets/tpnote-screenshot.png ./source/assets
cp ../assets/tpnote.svg ./source/assets

# Build
./build-doc-env/run-script ./make--index
./build-doc-env/run-script ./make--tpnote--manpage
./build-doc-env/run-script ./make--tpnote--manual
./build-doc-env/run-script ./make--symlinks

