#!/bin/sh

mkdir --parents ./build/html
mkdir --parents ./build/html/_downloads
mkdir --parents ./build/man/man1

# Html page
./md2man ./source/tp-note--manpage.md ./build/man/man1/tpnote.1
./docbook52pdf ./source/tp-note--manpage.md ./build/pdf/tp-note--manpage.pdf
./docbook52html ./source/tp-note--manpage.md ./build/html/tp-note--manpage.html

