#!/bin/sh

mkdir --parents ./build/html
mkdir --parents ./build/html/_downloads
mkdir --parents ./build/man/man1

# Html page
./markdown2pdf ./source/tpnote--manual.md ./build/pdf/tpnote--manual.pdf
./markdown2html ./source/tpnote--manual.md ./build/html/tpnote--manual.html

