#!/bin/bash
# Author: Jens Getreu

# apt install pandoc docbook-xsl-ns xsltproc
render () {
    ### parse args

    #set -x
    InPath="$1"
    InFile="${InPath##*/}"
    InFileExt="${InPath##*.}"
    InBase="${InFile%.*}"
    InDir="${InPath%/*}"
    if [ "$InDir" = "$InPath" ] ; then
        InDir="."
    fi

    OutPath="$2"
    OutFile="${OutPath##*/}"
    OutBase="${OutFile%.*}"
    OutDir="${OutPath%/*}"
    if [ "$OutDir" = "$OutPath" ] ; then
        OutDir="."
    fi


    ### Prepare

    HtmlPath="$OutDir/$OutBase.html"
    CssPath="$OutDir/web.css"
    mkdir -p "$OutDir"

    cp -r -L  "$InDir/assets/" "$OutDir"
    cp "$InDir/web.css" "$OutDir"

    ### Generate HTML

    # unfortunately the chain does not honor --number-section yet
    pandoc -s --to=html --from=markdown+yaml_metadata_block \
           --toc=true --number-sections -H "$CssPath" \
           -o "$HtmlPath" "$InPath"

}



### Main
# usage:
# render FILE [FILE]
# render report.md ./rendition/report.html

if [[ -n "${2/[ ]*\n/}" ]] ; then
        OutPath="$2"
else
        OutPath="${1%.*}.html" # $2 is empty
fi
render "$1" "$OutPath"


